name: Django-app workflow

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install depencies
        run: |
          # pip update
          python -m pip install --upgrade pip
          # flake8 with plugin install
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
          # install depencies
          pip install -r requirements.txt

      - name: Test with flake8 and Django tests
        run: |
          # flake8 tests
          python -m flake8
          cd infra_project/
          # Start Unittest
          python manage.py test